server:
  port: 88
  tomcat:
    uri-encoding: utf-8
    max-swallow-size: -1 # 不限制请求体大小

#日志级别
logging:
  level:
    root: info

spring:
  application:
    name: auth-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18848
#        username: nacos
#        password: nacos
